#define PROJECT_VERSION_MAJOR @ServerModule_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @ServerModule_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @ServerModule_VERSION_PATCH@
#define PROJECT_VERSION_TWEAK @ServerModule_VERSION_TWEAK@

#define PROJECT_BUILD_DATE @BUILD_DATE@
#define PROJECT_BUILD_TIME @BUILD_TIME@