#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_TWEAK 3

#define PROJECT_BUILD_DATE 2023/06/08
#define PROJECT_BUILD_TIME 16:09:08
