@startuml
'https://plantuml.com/deployment-diagram


scale 5000 width
folder SWPPGRPG <<model>> {

}

'============================================

folder App <<model>> {
}

folder System_Logowania <<subsystem>> {

}

folder System_Tworzenia_Treści <<subsystem>> {

}

folder System_Tworzenia_Postaci <<subsystem>> {

}

folder System_Tworzenia_Kampanii <<subsystem>> {

}

folder System_Muzyki <<subsystem>> {

}

folder System_Płatności <<subsystem>> {

}

folder System_Przebiegu_Gry <<subsystem>> {

}

folder System_Zarządzania_Postacią <<subsystem>> {

}

folder System_Kontaktu <<subsystem>> {

}

'============================================

folder Serwer <<model>> {
}

folder System_Zarządzania_Logami <<subsystem>> {

}

folder System_Detekcji_Błędów <<subsystem>> {

}

folder System_Zarządzania_Bazą_Danych <<subsystem>> {

}

folder System_Hostowania_Gier <<subsystem>> {

}

'============================================

App +-- System_Logowania
App +-- System_Tworzenia_Treści
System_Tworzenia_Treści +-- System_Tworzenia_Postaci
System_Tworzenia_Treści +-- System_Tworzenia_Kampanii
App +-- System_Muzyki
App +-- System_Płatności
App +-- System_Przebiegu_Gry
System_Przebiegu_Gry +-- System_Zarządzania_Postacią
App +-- System_Kontaktu

SWPPGRPG +-- Serwer
SWPPGRPG +-- App

Serwer +-- System_Zarządzania_Logami
System_Zarządzania_Logami +-- System_Detekcji_Błędów
Serwer +-- System_Zarządzania_Bazą_Danych
Serwer +-- System_Hostowania_Gier

'============================================


folder GUI <<modelLibrary>> {
}

folder Łączność_Z_Bazą_Danych <<modelLibrary>> {
}

folder Łącznik_Logowania <<framework>> {
}

folder Odtwarzanie_Muzyki <<modelLibrary>> {
}

folder Procesowanie_Płatności <<framework>> {
}

'============================================

System_Tworzenia_Treści ..> GUI : <<import>>
System_Przebiegu_Gry ..> GUI : <<import>>
System_Muzyki ..> GUI : <<import>>

System_Zarządzania_Bazą_Danych ..> Łączność_Z_Bazą_Danych : <<import>>

System_Logowania ..> Łącznik_Logowania : <<import>>

System_Muzyki ..> Odtwarzanie_Muzyki : <<import>>


System_Płatności ..> Procesowanie_Płatności : <<import>>


@enduml