#define PROJECT_VERSION_MAJOR @ClientModule_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @ClientModule_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @ClientModule_VERSION_PATCH@
#define PROJECT_VERSION_TWEAK @ClientModule_VERSION_TWEAK@

#define PROJECT_BUILD_DATE @BUILD_DATE@
#define PROJECT_BUILD_TIME @BUILD_TIME@