@startuml

	actor User
	actor Moderator

	rectangle PokerOnline {
		usecase Registration
	}

	'===============================================

	User -- PokerOnline
	Moderator -- PokerOnline



@enduml