#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_TWEAK 2

#define PROJECT_BUILD_DATE 2023/06/04
#define PROJECT_BUILD_TIME 01:41:57
