#define PROJECT_VERSION_MAJOR @ModelModule_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @ModelModule_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @ModelModule_VERSION_PATCH@
#define PROJECT_VERSION_TWEAK @ModelModule_VERSION_TWEAK@

#define PROJECT_BUILD_DATE @BUILD_DATE@
#define PROJECT_BUILD_TIME @BUILD_TIME@