#define PROJECT_VERSION_MAJOR @CommonModule_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @CommonModule_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @CommonModule_VERSION_PATCH@
#define PROJECT_VERSION_TWEAK @CommonModule_VERSION_TWEAK@

#define PROJECT_BUILD_DATE @BUILD_DATE@
#define PROJECT_BUILD_TIME @BUILD_TIME@